p8105 Homework 1
================
Yuanming Mao

This is my solution to HW1.

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Create a data frame with the specified elements.

``` r
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod","mod","mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame.

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.1146705

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.4

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can take the means of numbers and logical but not character or factor.

``` r
as.numeric(pull(prob1_df, samp))
```

    ##  [1]  1.104361146 -0.708299411 -0.778511528 -0.203594428  0.337636719
    ##  [6]  0.091973415  0.731390686 -0.486605942 -0.006264722 -1.228791351

``` r
as.numeric(pull(prob1_df, samp_gt_0))
```

    ##  [1] 1 0 0 0 1 1 1 0 0 0

``` r
as.numeric(pull(prob1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1_df, factor_vec))
```

    ##  [1] 2 2 2 3 3 3 3 1 1 1

The logic vector is converted to numeric 0 and 1, the character vector
is converted to NA for all elements, and the factor vector is converted
to numeric. It helps explain that R regards true as 1 and false as 0
automatically. And it shows that a factor vector can be converted to
numeric, but a character vector cannot.

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 1.10436115 0.00000000 0.00000000 0.00000000 0.33763672 0.09197342
    ##  [7] 0.73139069 0.00000000 0.00000000 0.00000000

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1]  2.208722292 -0.708299411 -0.778511528 -0.203594428  0.675273439
    ##  [6]  0.183946830  1.462781372 -0.486605942 -0.006264722 -1.228791351

## Problem 2

``` r
data("penguins", package = "palmerpenguins")

summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

This dataset includes data of location and physical features of 3
species of penguins. Important variables include species, island where
the penguin is from, bill length and depth in mm, flipper length in mm,
body mass in gram, sex, and year. Three penguins species include Adelie,
Chinstrap and Gentoo. Three islands that these penguins are from include
Biscoe, Dream, and Torgersen.Bill length ranges from 32.10 to 59.60 mm,
bill depth from 13.10 to 21.50 mm, flipper length from 172.0 to 231.0
mm, and body mass from 2700 to 6300 grams.

This dataset has 344 rows and 8 columns.

The mean flipper length of those penguins is 200.9152047 mm.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ym2770_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf",height=4,width=4)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
